<?php

use Illuminate\Database\Seeder;


class CountriesTableSeeder extends Seeder {

    public function run()
    {
        DB::table("countries")->delete();


		 DB::table("countries")->insert(array("code" => "AF", "name" => "Afghanistan"));
		 DB::table("countries")->insert(array("code" => "AX", "name" => "�land Islands"));
		 DB::table("countries")->insert(array("code" => "AL", "name" => "Albania"));
		 DB::table("countries")->insert(array("code" => "DZ", "name" => "Algeria"));
		 DB::table("countries")->insert(array("code" => "AS", "name" => "American Samoa"));
		 DB::table("countries")->insert(array("code" => "AD", "name" => "Andorra"));
		 DB::table("countries")->insert(array("code" => "AO", "name" => "Angola"));
		 DB::table("countries")->insert(array("code" => "AI", "name" => "Anguilla"));
		 DB::table("countries")->insert(array("code" => "AQ", "name" => "Antarctica"));
		 DB::table("countries")->insert(array("code" => "AG", "name" => "Antigua and Barbuda"));
		 DB::table("countries")->insert(array("code" => "AR", "name" => "Argentina"));
		 DB::table("countries")->insert(array("code" => "AM", "name" => "Armenia"));
		 DB::table("countries")->insert(array("code" => "AW", "name" => "Aruba"));
		 DB::table("countries")->insert(array("code" => "AU", "name" => "Australia"));
		 DB::table("countries")->insert(array("code" => "AT", "name" => "Austria"));
		 DB::table("countries")->insert(array("code" => "AZ", "name" => "Azerbaijan"));
		 DB::table("countries")->insert(array("code" => "BS", "name" => "Bahamas"));
		 DB::table("countries")->insert(array("code" => "BH", "name" => "Bahrain"));
		 DB::table("countries")->insert(array("code" => "BD", "name" => "Bangladesh"));
		 DB::table("countries")->insert(array("code" => "BB", "name" => "Barbados"));
		 DB::table("countries")->insert(array("code" => "BY", "name" => "Belarus"));
		 DB::table("countries")->insert(array("code" => "BE", "name" => "Belgium"));
		 DB::table("countries")->insert(array("code" => "BZ", "name" => "Belize"));
		 DB::table("countries")->insert(array("code" => "BJ", "name" => "Benin"));
		 DB::table("countries")->insert(array("code" => "BM", "name" => "Bermuda"));
		 DB::table("countries")->insert(array("code" => "BT", "name" => "Bhutan"));
		 DB::table("countries")->insert(array("code" => "BO", "name" => "Bolivia (Plurinational State of)"));
		 DB::table("countries")->insert(array("code" => "BQ", "name" => "Bonaire  Sint Eustatius and Saba"));
		 DB::table("countries")->insert(array("code" => "BA", "name" => "Bosnia and Herzegovina"));
		 DB::table("countries")->insert(array("code" => "BW", "name" => "Botswana"));
		 DB::table("countries")->insert(array("code" => "BV", "name" => "Bouvet Island"));
		 DB::table("countries")->insert(array("code" => "BR", "name" => "Brazil"));
		 DB::table("countries")->insert(array("code" => "IO", "name" => "British Indian Ocean Territory"));
		 DB::table("countries")->insert(array("code" => "BN", "name" => "Brunei Darussalam"));
		 DB::table("countries")->insert(array("code" => "BG", "name" => "Bulgaria"));
		 DB::table("countries")->insert(array("code" => "BF", "name" => "Burkina Faso"));
		 DB::table("countries")->insert(array("code" => "BI", "name" => "Burundi"));
		 DB::table("countries")->insert(array("code" => "KH", "name" => "Cambodia"));
		 DB::table("countries")->insert(array("code" => "CM", "name" => "Cameroon"));
		 DB::table("countries")->insert(array("code" => "CA", "name" => "Canada"));
		 DB::table("countries")->insert(array("code" => "CV", "name" => "Cabo Verde"));
		 DB::table("countries")->insert(array("code" => "KY", "name" => "Cayman Islands"));
		 DB::table("countries")->insert(array("code" => "CF", "name" => "Central African Republic"));
		 DB::table("countries")->insert(array("code" => "TD", "name" => "Chad"));
		 DB::table("countries")->insert(array("code" => "CL", "name" => "Chile"));
		 DB::table("countries")->insert(array("code" => "CN", "name" => "China"));
		 DB::table("countries")->insert(array("code" => "CX", "name" => "Christmas Island"));
		 DB::table("countries")->insert(array("code" => "CC", "name" => "Cocos (Keeling) Islands"));
		 DB::table("countries")->insert(array("code" => "CO", "name" => "Colombia"));
		 DB::table("countries")->insert(array("code" => "KM", "name" => "Comoros"));
		 DB::table("countries")->insert(array("code" => "CG", "name" => "Congo"));
		 DB::table("countries")->insert(array("code" => "CD", "name" => "Congo (Democratic Republic of the)"));
		 DB::table("countries")->insert(array("code" => "CK", "name" => "Cook Islands"));
		 DB::table("countries")->insert(array("code" => "CR", "name" => "Costa Rica"));
		 DB::table("countries")->insert(array("code" => "CI", "name" => "C�te d'Ivoire"));
		 DB::table("countries")->insert(array("code" => "HR", "name" => "Croatia"));
		 DB::table("countries")->insert(array("code" => "CU", "name" => "Cuba"));
		 DB::table("countries")->insert(array("code" => "CW", "name" => "Cura�ao"));
		 DB::table("countries")->insert(array("code" => "CY", "name" => "Cyprus"));
		 DB::table("countries")->insert(array("code" => "CZ", "name" => "Czech Republic"));
		 DB::table("countries")->insert(array("code" => "DK", "name" => "Denmark"));
		 DB::table("countries")->insert(array("code" => "DJ", "name" => "Djibouti"));
		 DB::table("countries")->insert(array("code" => "DM", "name" => "Dominica"));
		 DB::table("countries")->insert(array("code" => "DO", "name" => "Dominican Republic"));
		 DB::table("countries")->insert(array("code" => "EC", "name" => "Ecuador"));
		 DB::table("countries")->insert(array("code" => "EG", "name" => "Egypt"));
		 DB::table("countries")->insert(array("code" => "SV", "name" => "El Salvador"));
		 DB::table("countries")->insert(array("code" => "GQ", "name" => "Equatorial Guinea"));
		 DB::table("countries")->insert(array("code" => "ER", "name" => "Eritrea"));
		 DB::table("countries")->insert(array("code" => "EE", "name" => "Estonia"));
		 DB::table("countries")->insert(array("code" => "ET", "name" => "Ethiopia"));
		 DB::table("countries")->insert(array("code" => "FK", "name" => "Falkland Islands (Malvinas)"));
		 DB::table("countries")->insert(array("code" => "FO", "name" => "Faroe Islands"));
		 DB::table("countries")->insert(array("code" => "FJ", "name" => "Fiji"));
		 DB::table("countries")->insert(array("code" => "FI", "name" => "Finland"));
		 DB::table("countries")->insert(array("code" => "FR", "name" => "France"));
		 DB::table("countries")->insert(array("code" => "GF", "name" => "French Guiana"));
		 DB::table("countries")->insert(array("code" => "PF", "name" => "French Polynesia"));
		 DB::table("countries")->insert(array("code" => "TF", "name" => "French Southern Territories"));
		 DB::table("countries")->insert(array("code" => "GA", "name" => "Gabon"));
		 DB::table("countries")->insert(array("code" => "GM", "name" => "Gambia"));
		 DB::table("countries")->insert(array("code" => "GE", "name" => "Georgia"));
		 DB::table("countries")->insert(array("code" => "DE", "name" => "Germany"));
		 DB::table("countries")->insert(array("code" => "GH", "name" => "Ghana"));
		 DB::table("countries")->insert(array("code" => "GI", "name" => "Gibraltar"));
		 DB::table("countries")->insert(array("code" => "GR", "name" => "Greece"));
		 DB::table("countries")->insert(array("code" => "GL", "name" => "Greenland"));
		 DB::table("countries")->insert(array("code" => "GD", "name" => "Grenada"));
		 DB::table("countries")->insert(array("code" => "GP", "name" => "Guadeloupe"));
		 DB::table("countries")->insert(array("code" => "GU", "name" => "Guam"));
		 DB::table("countries")->insert(array("code" => "GT", "name" => "Guatemala"));
		 DB::table("countries")->insert(array("code" => "GG", "name" => "Guernsey"));
		 DB::table("countries")->insert(array("code" => "GN", "name" => "Guinea"));
		 DB::table("countries")->insert(array("code" => "GW", "name" => "Guinea-Bissau"));
		 DB::table("countries")->insert(array("code" => "GY", "name" => "Guyana"));
		 DB::table("countries")->insert(array("code" => "HT", "name" => "Haiti"));
		 DB::table("countries")->insert(array("code" => "HM", "name" => "Heard Island and McDonald Islands"));
		 DB::table("countries")->insert(array("code" => "VA", "name" => "Holy See"));
		 DB::table("countries")->insert(array("code" => "HN", "name" => "Honduras"));
		 DB::table("countries")->insert(array("code" => "HK", "name" => "Hong Kong"));
		 DB::table("countries")->insert(array("code" => "HU", "name" => "Hungary"));
		 DB::table("countries")->insert(array("code" => "IS", "name" => "Iceland"));
		 DB::table("countries")->insert(array("code" => "IN", "name" => "India"));
		 DB::table("countries")->insert(array("code" => "ID", "name" => "Indonesia"));
		 DB::table("countries")->insert(array("code" => "IR", "name" => "Iran (Islamic Republic of)"));
		 DB::table("countries")->insert(array("code" => "IQ", "name" => "Iraq"));
		 DB::table("countries")->insert(array("code" => "IE", "name" => "Ireland"));
		 DB::table("countries")->insert(array("code" => "IM", "name" => "Isle of Man"));
		 DB::table("countries")->insert(array("code" => "IL", "name" => "Israel"));
		 DB::table("countries")->insert(array("code" => "IT", "name" => "Italy"));
		 DB::table("countries")->insert(array("code" => "JM", "name" => "Jamaica"));
		 DB::table("countries")->insert(array("code" => "JP", "name" => "Japan"));
		 DB::table("countries")->insert(array("code" => "JE", "name" => "Jersey"));
		 DB::table("countries")->insert(array("code" => "JO", "name" => "Jordan"));
		 DB::table("countries")->insert(array("code" => "KZ", "name" => "Kazakhstan"));
		 DB::table("countries")->insert(array("code" => "KE", "name" => "Kenya"));
		 DB::table("countries")->insert(array("code" => "KI", "name" => "Kiribati"));
		 DB::table("countries")->insert(array("code" => "KP", "name" => "Korea (Democratic People\"s Republic of)"));
		 DB::table("countries")->insert(array("code" => "KR", "name" => "Korea (Republic of)"));
		 DB::table("countries")->insert(array("code" => "KW", "name" => "Kuwait"));
		 DB::table("countries")->insert(array("code" => "KG", "name" => "Kyrgyzstan"));
		 DB::table("countries")->insert(array("code" => "LA", "name" => "Lao People\"s Democratic Republic"));
		 DB::table("countries")->insert(array("code" => "LV", "name" => "Latvia"));
		 DB::table("countries")->insert(array("code" => "LB", "name" => "Lebanon"));
		 DB::table("countries")->insert(array("code" => "LS", "name" => "Lesotho"));
		 DB::table("countries")->insert(array("code" => "LR", "name" => "Liberia"));
		 DB::table("countries")->insert(array("code" => "LY", "name" => "Libya"));
		 DB::table("countries")->insert(array("code" => "LI", "name" => "Liechtenstein"));
		 DB::table("countries")->insert(array("code" => "LT", "name" => "Lithuania"));
		 DB::table("countries")->insert(array("code" => "LU", "name" => "Luxembourg"));
		 DB::table("countries")->insert(array("code" => "MO", "name" => "Macao"));
		 DB::table("countries")->insert(array("code" => "MK", "name" => "Macedonia (the former Yugoslav Republic of)"));
		 DB::table("countries")->insert(array("code" => "MG", "name" => "Madagascar"));
		 DB::table("countries")->insert(array("code" => "MW", "name" => "Malawi"));
		 DB::table("countries")->insert(array("code" => "MY", "name" => "Malaysia"));
		 DB::table("countries")->insert(array("code" => "MV", "name" => "Maldives"));
		 DB::table("countries")->insert(array("code" => "ML", "name" => "Mali"));
		 DB::table("countries")->insert(array("code" => "MT", "name" => "Malta"));
		 DB::table("countries")->insert(array("code" => "MH", "name" => "Marshall Islands"));
		 DB::table("countries")->insert(array("code" => "MQ", "name" => "Martinique"));
		 DB::table("countries")->insert(array("code" => "MR", "name" => "Mauritania"));
		 DB::table("countries")->insert(array("code" => "MU", "name" => "Mauritius"));
		 DB::table("countries")->insert(array("code" => "YT", "name" => "Mayotte"));
		 DB::table("countries")->insert(array("code" => "MX", "name" => "Mexico"));
		 DB::table("countries")->insert(array("code" => "FM", "name" => "Micronesia (Federated States of)"));
		 DB::table("countries")->insert(array("code" => "MD", "name" => "Moldova (Republic of)"));
		 DB::table("countries")->insert(array("code" => "MC", "name" => "Monaco"));
		 DB::table("countries")->insert(array("code" => "MN", "name" => "Mongolia"));
		 DB::table("countries")->insert(array("code" => "ME", "name" => "Montenegro"));
		 DB::table("countries")->insert(array("code" => "MS", "name" => "Montserrat"));
		 DB::table("countries")->insert(array("code" => "MA", "name" => "Morocco"));
		 DB::table("countries")->insert(array("code" => "MZ", "name" => "Mozambique"));
		 DB::table("countries")->insert(array("code" => "MM", "name" => "Myanmar"));
		 DB::table("countries")->insert(array("code" => "NA", "name" => "Namibia"));
		 DB::table("countries")->insert(array("code" => "NR", "name" => "Nauru"));
		 DB::table("countries")->insert(array("code" => "NP", "name" => "Nepal"));
		 DB::table("countries")->insert(array("code" => "NL", "name" => "Netherlands"));
		 DB::table("countries")->insert(array("code" => "NC", "name" => "New Caledonia"));
		 DB::table("countries")->insert(array("code" => "NZ", "name" => "New Zealand"));
		 DB::table("countries")->insert(array("code" => "NI", "name" => "Nicaragua"));
		 DB::table("countries")->insert(array("code" => "NE", "name" => "Niger"));
		 DB::table("countries")->insert(array("code" => "NG", "name" => "Nigeria"));
		 DB::table("countries")->insert(array("code" => "NU", "name" => "Niue"));
		 DB::table("countries")->insert(array("code" => "NF", "name" => "Norfolk Island"));
		 DB::table("countries")->insert(array("code" => "MP", "name" => "Northern Mariana Islands"));
		 DB::table("countries")->insert(array("code" => "NO", "name" => "Norway"));
		 DB::table("countries")->insert(array("code" => "OM", "name" => "Oman"));
		 DB::table("countries")->insert(array("code" => "PK", "name" => "Pakistan"));
		 DB::table("countries")->insert(array("code" => "PW", "name" => "Palau"));
		 DB::table("countries")->insert(array("code" => "PS", "name" => "Palestine State of"));
		 DB::table("countries")->insert(array("code" => "PA", "name" => "Panama"));
		 DB::table("countries")->insert(array("code" => "PG", "name" => "Papua New Guinea"));
		 DB::table("countries")->insert(array("code" => "PY", "name" => "Paraguay"));
		 DB::table("countries")->insert(array("code" => "PE", "name" => "Peru"));
		 DB::table("countries")->insert(array("code" => "PH", "name" => "Philippines"));
		 DB::table("countries")->insert(array("code" => "PN", "name" => "Pitcairn"));
		 DB::table("countries")->insert(array("code" => "PL", "name" => "Poland"));
		 DB::table("countries")->insert(array("code" => "PT", "name" => "Portugal"));
		 DB::table("countries")->insert(array("code" => "PR", "name" => "Puerto Rico"));
		 DB::table("countries")->insert(array("code" => "QA", "name" => "Qatar"));
		 DB::table("countries")->insert(array("code" => "RE", "name" => "R�union"));
		 DB::table("countries")->insert(array("code" => "RO", "name" => "Romania"));
		 DB::table("countries")->insert(array("code" => "RU", "name" => "Russian Federation"));
		 DB::table("countries")->insert(array("code" => "RW", "name" => "Rwanda"));
		 DB::table("countries")->insert(array("code" => "BL", "name" => "Saint Barth�lemy"));
		 DB::table("countries")->insert(array("code" => "SH", "name" => "Saint Helena Ascension and Tristan da Cunha"));
		 DB::table("countries")->insert(array("code" => "KN", "name" => "Saint Kitts and Nevis"));
		 DB::table("countries")->insert(array("code" => "LC", "name" => "Saint Lucia"));
		 DB::table("countries")->insert(array("code" => "MF", "name" => "Saint Martin (French part)"));
		 DB::table("countries")->insert(array("code" => "PM", "name" => "Saint Pierre and Miquelon"));
		 DB::table("countries")->insert(array("code" => "VC", "name" => "Saint Vincent and the Grenadines"));
		 DB::table("countries")->insert(array("code" => "WS", "name" => "Samoa"));
		 DB::table("countries")->insert(array("code" => "SM", "name" => "San Marino"));
		 DB::table("countries")->insert(array("code" => "ST", "name" => "Sao Tome and Principe"));
		 DB::table("countries")->insert(array("code" => "SA", "name" => "Saudi Arabia"));
		 DB::table("countries")->insert(array("code" => "SN", "name" => "Senegal"));
		 DB::table("countries")->insert(array("code" => "RS", "name" => "Serbia"));
		 DB::table("countries")->insert(array("code" => "SC", "name" => "Seychelles"));
		 DB::table("countries")->insert(array("code" => "SL", "name" => "Sierra Leone"));
		 DB::table("countries")->insert(array("code" => "SG", "name" => "Singapore"));
		 DB::table("countries")->insert(array("code" => "SX", "name" => "Sint Maarten (Dutch part)"));
		 DB::table("countries")->insert(array("code" => "SK", "name" => "Slovakia"));
		 DB::table("countries")->insert(array("code" => "SI", "name" => "Slovenia"));
		 DB::table("countries")->insert(array("code" => "SB", "name" => "Solomon Islands"));
		 DB::table("countries")->insert(array("code" => "SO", "name" => "Somalia"));
		 DB::table("countries")->insert(array("code" => "ZA", "name" => "South Africa"));
		 DB::table("countries")->insert(array("code" => "GS", "name" => "South Georgia and the South Sandwich Islands"));
		 DB::table("countries")->insert(array("code" => "SS", "name" => "South Sudan"));
		 DB::table("countries")->insert(array("code" => "ES", "name" => "Esspaña"));
		 DB::table("countries")->insert(array("code" => "LK", "name" => "Sri Lanka"));
		 DB::table("countries")->insert(array("code" => "SD", "name" => "Sudan"));
		 DB::table("countries")->insert(array("code" => "SR", "name" => "Suricode"));
		 DB::table("countries")->insert(array("code" => "SJ", "name" => "Svalbard and Jan Mayen"));
		 DB::table("countries")->insert(array("code" => "SZ", "name" => "Swaziland"));
		 DB::table("countries")->insert(array("code" => "SE", "name" => "Sweden"));
		 DB::table("countries")->insert(array("code" => "CH", "name" => "Switzerland"));
		 DB::table("countries")->insert(array("code" => "SY", "name" => "Syrian Arab Republic"));
		 DB::table("countries")->insert(array("code" => "TW", "name" => "Taiwan Province of China"));
		 DB::table("countries")->insert(array("code" => "TJ", "name" => "Tajikistan"));
		 DB::table("countries")->insert(array("code" => "TZ", "name" => "Tanzania United Republic of"));
		 DB::table("countries")->insert(array("code" => "TH", "name" => "Thailand"));
		 DB::table("countries")->insert(array("code" => "TL", "name" => "Timor-Leste"));
		 DB::table("countries")->insert(array("code" => "TG", "name" => "Togo"));
		 DB::table("countries")->insert(array("code" => "TK", "name" => "Tokelau"));
		 DB::table("countries")->insert(array("code" => "TO", "name" => "Tonga"));
		 DB::table("countries")->insert(array("code" => "TT", "name" => "Trinidad and Tobago"));
		 DB::table("countries")->insert(array("code" => "TN", "name" => "Tunisia"));
		 DB::table("countries")->insert(array("code" => "TR", "name" => "Turkey"));
		 DB::table("countries")->insert(array("code" => "TM", "name" => "Turkmenistan"));
		 DB::table("countries")->insert(array("code" => "TC", "name" => "Turks and Caicos Islands"));
		 DB::table("countries")->insert(array("code" => "TV", "name" => "Tuvalu"));
		 DB::table("countries")->insert(array("code" => "UG", "name" => "Uganda"));
		 DB::table("countries")->insert(array("code" => "UA", "name" => "Ukraine"));
		 DB::table("countries")->insert(array("code" => "AE", "name" => "United Arab Emirates"));
		 DB::table("countries")->insert(array("code" => "GB", "name" => "United Kingdom of Great Britain and Northern Ireland"));
		 DB::table("countries")->insert(array("code" => "US", "name" => "United States of America"));
		 DB::table("countries")->insert(array("code" => "UM", "name" => "United States Minor Outlying Islands"));
		 DB::table("countries")->insert(array("code" => "UY", "name" => "Uruguay"));
		 DB::table("countries")->insert(array("code" => "UZ", "name" => "Uzbekistan"));
		 DB::table("countries")->insert(array("code" => "VU", "name" => "Vanuatu"));
		 DB::table("countries")->insert(array("code" => "VE", "name" => "Venezuela (Bolivarian Republic of)"));
		 DB::table("countries")->insert(array("code" => "VN", "name" => "Viet Nam"));
		 DB::table("countries")->insert(array("code" => "VG", "name" => "Virgin Islands (British)"));
		 DB::table("countries")->insert(array("code" => "VI", "name" => "Virgin Islands (U.S.)"));
		 DB::table("countries")->insert(array("code" => "WF", "name" => "Wallis and Futuna"));
		 DB::table("countries")->insert(array("code" => "EH", "name" => "Western Sahara"));
		 DB::table("countries")->insert(array("code" => "YE", "name" => "Yemen"));
		 DB::table("countries")->insert(array("code" => "ZM", "name" => "Zambia"));
		 DB::table("countries")->insert(array("code" => "ZW", "name" => "Zimbabwe"));
    }

}
